blueprint:
  name: Covercast-MGMT
  description: Send a image to covercast
  domain: automation
  source_url: https://raw.githubusercontent.com/alfredit/CoverCast/refs/heads/main/blueprint/auto-covercast.yml
  author: AlfredIT
  input:
    brightness-selector:
      name: Brightness Selector
      selector:
        entity:
          filter:
            domain: input_number
    covercast-switch:
      name: CoverCast switch
      selector:
        entity:
          filter:
            domain: switch
    covercast-notifier:
      name: CoverCast notifier
      selector:
        entity:
          filter:
            domain: notify
